import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { RecoilRootWrapper } from "@/components/RecoilRootWrapper";
import { Zen_Kaku_Gothic_New } from "next/font/google";
import { TabNavigation } from "@/components/TabNavigation";
import { Sawarabi_Mincho } from "next/font/google";

export const font = Zen_Kaku_Gothic_New({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

export const font2 = Sawarabi_Mincho({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "たまごかけごはん.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>
      <body className={font.className}>
        <RecoilRootWrapper>
          <Header />
          <main className="py-16 w-screen">
            <div className="w-full">{children}</div>
          </main>
          <TabNavigation />
        </RecoilRootWrapper>
      </body>
    </html>
  );
}
